### ISSUE TITLE
Will fail to compile with ESPHome 2026.4.x

### ISSUE THREAD

**Issue by fawick** [HarmEllis/esphome-somfy-cover-remote#10]
ESPHome PR https://github.com/esphome/esphome/pull/15313 moved the TimeBasedCover class into a sub-folder. It was released with ESPHome 2026.4.

[I filed an issue with issue with ESPHome](https://github.com/esphome/esphome/issues/15872) and received [the reply that it won't be fixed and how to deal with situation](https://github.com/esphome/esphome/issues/15872#issuecomment-4282350385). In short: `time_based_cover.{cpp,h}` needs to be vendored with the custom component.

**Comment by steffen-le** [comment]
I have the same issue. The log is:
In file included from src/esphome/components/somfy_cover/somfy_cover.cpp:2:
src/esphome/components/somfy_cover/somfy_cover.h:5:10: fatal error: esphome/components/time_based/time_based_cover.h: No such file or directory
    5 | #include "esphome/components/time_based/time_based_cover.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/somfy/src/esphome/components/somfy_cover/somfy_cover.cpp.o] Error 1
There seems to be problem in loading the file from the repository... 

New configuration also creates the same problem...

Thanks for your help!

**Comment by ftpproxy** [comment]
CorjanV has already made a working patch for this.

https://github.com/CorjanV/esphome-somfy-cover-remote/tree/feature/official-cc1101-remote-transmitter

@CorjanV please create a pull request for it

**Comment by HarmEllis** [comment]
Thanks @fawick and @steffen-le for reporting and testing this, and thanks @CorjanV for the PR.

This is now fixed in v3.0.1:
https://github.com/HarmEllis/esphome-somfy-cover-remote/releases/tag/v3.0.1

If you’re still seeing compile errors, please clean the build files and recompile.

If it still fails after that, share the first error block and your ESPHome version, and I’ll follow up.
